import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(new URL('..', import.meta.url).pathname);
const sourcesDir = path.join(root, 'src', 'data', 'sources', 'thailand-geodata');
const provincesPath = path.join(sourcesDir, 'provinces.csv');
const districtsPath = path.join(sourcesDir, 'districts.csv');
const subdistrictsPath = path.join(sourcesDir, 'sub_districts.csv');
const outThaiPath = path.join(root, 'src', 'data', 'compact-data-th.ts');
const outEnglishPath = path.join(root, 'src', 'data', 'compact-data-en.ts');
const legacyOutPath = path.join(root, 'src', 'data', 'compact-data.ts');

function readCsv(filePath) {
  const text = fs.readFileSync(filePath, 'utf8').replace(/^\uFEFF/, '');
  const [headerLine, ...lines] = text.split(/\r?\n/).filter(Boolean);
  const headers = parseCsvLine(headerLine);

  return lines.map((line) => {
    const values = parseCsvLine(line);
    return Object.fromEntries(headers.map((header, index) => [header, values[index] ?? '']));
  });
}

function parseCsvLine(line) {
  const values = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i += 1) {
    const char = line[i];

    if (char === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (char === ',' && !inQuotes) {
      values.push(current);
      current = '';
      continue;
    }

    current += char;
  }

  values.push(current);
  return values;
}

function intern(map, list, value) {
  const existing = map.get(value);
  if (existing !== undefined) return existing;
  const next = list.length;
  list.push(value);
  map.set(value, next);
  return next;
}

function buildDatasets() {
  const provinces = readCsv(provincesPath);
  const districts = readCsv(districtsPath);
  const subdistricts = readCsv(subdistrictsPath);

  const provinceById = new Map(provinces.map((row) => [row.PROVINCE_ID, row]));
  const districtById = new Map(districts.map((row) => [row.DISTRICT_ID, row]));

  const provinceNames = [];
  const districtNames = [];
  const subdistrictNames = [];
  const provinceNamesEn = [];
  const districtNamesEn = [];
  const subdistrictNamesEn = [];

  const provinceIndex = new Map();
  const districtIndex = new Map();
  const subdistrictIndex = new Map();

  const rows = [];
  for (const row of subdistricts) {
    const district = districtById.get(row.DISTRICT_ID);
    if (!district) throw new Error(`Missing district for subdistrict ${row.SUB_DISTRICT_ID}`);

    const province = provinceById.get(district.PROVINCE_ID);
    if (!province) throw new Error(`Missing province for district ${district.DISTRICT_ID}`);

    const provinceNameIndex = intern(provinceIndex, provinceNames, province.PROVINCE_THAI);
    provinceNamesEn[provinceNameIndex] = province.PROVINCE_ENGLISH;

    const districtNameIndex = intern(districtIndex, districtNames, district.DISTRICT_THAI);
    districtNamesEn[districtNameIndex] = district.DISTRICT_ENGLISH;

    const subdistrictNameIndex = intern(subdistrictIndex, subdistrictNames, row.SUB_DISTRICT_THAI);
    subdistrictNamesEn[subdistrictNameIndex] = row.SUB_DISTRICT_ENGLISH;

    rows.push([
      provinceNameIndex,
      Number(province.CODE) || -1,
      districtNameIndex,
      Number(district.DISTRICT_CODE) || -1,
      subdistrictNameIndex,
      Number(row.SUB_DISTRICT_CODE) || -1,
      Number(row.POSTAL_CODE) || -1,
    ]);
  }

  rows.sort((a, b) =>
    provinceNames[a[0]].localeCompare(provinceNames[b[0]], 'th') ||
    districtNames[a[2]].localeCompare(districtNames[b[2]], 'th') ||
    subdistrictNames[a[4]].localeCompare(subdistrictNames[b[4]], 'th') ||
    a[6] - b[6]
  );

  return {
    provinceNames,
    districtNames,
    subdistrictNames,
    provinceNamesEn,
    districtNamesEn,
    subdistrictNamesEn,
    rows,
    sourceCounts: {
      provinces: provinces.length,
      districts: districts.length,
      subdistricts: subdistricts.length,
    },
  };
}

function packList(values) {
  return values.join('\n');
}

function packRows(rows) {
  return rows
    .map((row) => row.map((value) => value.toString(36)).join('.'))
    .join('|');
}

function serializeThai({ provinceNames, districtNames, subdistrictNames, rows }) {
  return `// Auto-generated by scripts/generate-data.mjs\n` +
    `// Source: Dhanabhon/thailand-geodata (MIT)\n\n` +
    `import { decodePackedList, decodePackedRows } from '../lib/packed.js';\n\n` +
    `export type ThaiAddressRow = [\n` +
    `  provinceNameIndex: number,\n` +
    `  provinceCode: number,\n` +
    `  districtNameIndex: number,\n` +
    `  districtCode: number,\n` +
    `  subdistrictNameIndex: number,\n` +
    `  subdistrictCode: number,\n` +
    `  postalCode: number,\n` +
    `];\n\n` +
    `const PACKED_THAI_ADDRESS_PROVINCES = ${JSON.stringify(packList(provinceNames))};\n\n` +
    `const PACKED_THAI_ADDRESS_DISTRICTS = ${JSON.stringify(packList(districtNames))};\n\n` +
    `const PACKED_THAI_ADDRESS_SUBDISTRICTS = ${JSON.stringify(packList(subdistrictNames))};\n\n` +
    `const PACKED_THAI_ADDRESS_ROWS = ${JSON.stringify(packRows(rows))};\n\n` +
    `export const THAI_ADDRESS_PROVINCES: readonly string[] = decodePackedList(PACKED_THAI_ADDRESS_PROVINCES);\n\n` +
    `export const THAI_ADDRESS_DISTRICTS: readonly string[] = decodePackedList(PACKED_THAI_ADDRESS_DISTRICTS);\n\n` +
    `export const THAI_ADDRESS_SUBDISTRICTS: readonly string[] = decodePackedList(PACKED_THAI_ADDRESS_SUBDISTRICTS);\n\n` +
    `export const THAI_ADDRESS_ROWS: readonly ThaiAddressRow[] = decodePackedRows(PACKED_THAI_ADDRESS_ROWS);\n`;
}

function serializeEnglish({ provinceNames, districtNames, subdistrictNames, provinceNamesEn, districtNamesEn, subdistrictNamesEn, rows }) {
  return `// Auto-generated by scripts/generate-data.mjs\n` +
    `// Source: Dhanabhon/thailand-geodata (MIT)\n\n` +
    `import { decodePackedList, decodePackedRows } from '../lib/packed.js';\n\n` +
    `export type ThaiAddressRow = [\n` +
    `  provinceNameIndex: number,\n` +
    `  provinceCode: number,\n` +
    `  districtNameIndex: number,\n` +
    `  districtCode: number,\n` +
    `  subdistrictNameIndex: number,\n` +
    `  subdistrictCode: number,\n` +
    `  postalCode: number,\n` +
    `];\n\n` +
    `const PACKED_THAI_ADDRESS_PROVINCES = ${JSON.stringify(packList(provinceNames))};\n\n` +
    `const PACKED_THAI_ADDRESS_PROVINCES_EN = ${JSON.stringify(packList(provinceNamesEn))};\n\n` +
    `const PACKED_THAI_ADDRESS_DISTRICTS = ${JSON.stringify(packList(districtNames))};\n\n` +
    `const PACKED_THAI_ADDRESS_DISTRICTS_EN = ${JSON.stringify(packList(districtNamesEn))};\n\n` +
    `const PACKED_THAI_ADDRESS_SUBDISTRICTS = ${JSON.stringify(packList(subdistrictNames))};\n\n` +
    `const PACKED_THAI_ADDRESS_SUBDISTRICTS_EN = ${JSON.stringify(packList(subdistrictNamesEn))};\n\n` +
    `const PACKED_THAI_ADDRESS_ROWS = ${JSON.stringify(packRows(rows))};\n\n` +
    `export const THAI_ADDRESS_PROVINCES: readonly string[] = decodePackedList(PACKED_THAI_ADDRESS_PROVINCES);\n\n` +
    `export const THAI_ADDRESS_PROVINCES_EN: readonly string[] = decodePackedList(PACKED_THAI_ADDRESS_PROVINCES_EN);\n\n` +
    `export const THAI_ADDRESS_DISTRICTS: readonly string[] = decodePackedList(PACKED_THAI_ADDRESS_DISTRICTS);\n\n` +
    `export const THAI_ADDRESS_DISTRICTS_EN: readonly string[] = decodePackedList(PACKED_THAI_ADDRESS_DISTRICTS_EN);\n\n` +
    `export const THAI_ADDRESS_SUBDISTRICTS: readonly string[] = decodePackedList(PACKED_THAI_ADDRESS_SUBDISTRICTS);\n\n` +
    `export const THAI_ADDRESS_SUBDISTRICTS_EN: readonly string[] = decodePackedList(PACKED_THAI_ADDRESS_SUBDISTRICTS_EN);\n\n` +
    `export const THAI_ADDRESS_ROWS: readonly ThaiAddressRow[] = decodePackedRows(PACKED_THAI_ADDRESS_ROWS);\n`;
}

const dataset = buildDatasets();
fs.writeFileSync(outThaiPath, serializeThai(dataset));
fs.writeFileSync(outEnglishPath, serializeEnglish(dataset));
if (fs.existsSync(legacyOutPath)) fs.rmSync(legacyOutPath);

console.log(
  `wrote ${dataset.rows.length} rows (${dataset.sourceCounts.provinces} provinces, ${dataset.sourceCounts.districts} districts, ${dataset.sourceCounts.subdistricts} subdistricts from source)`
);
console.log(`- ${path.relative(root, outThaiPath)}`);
console.log(`- ${path.relative(root, outEnglishPath)}`);
